import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import * as THREE from "three";
import FOG from "vanta/dist/vanta.fog.min"
import 'animate.css';

export default function Home() {
  const [vantaEffect, setVantaEffect] = useState(0);
  const vantaRef = useRef(null);
  useEffect(() => {
    if (!vantaEffect) {
      setVantaEffect(
        FOG({
          el: vantaRef.current,
          THREE: THREE,
          mouseControls: true,
  touchControls: true,
  gyroControls: false,
  minHeight: 200.00,
  minWidth: 200.00,
  highlightColor: 0x2ff7,
  midtoneColor: 0xffffff,
  lowlightColor: 0xffffff,
  baseColor: 0xffffff
        })
      );
    }
    return () => {
      if (vantaEffect) vantaEffect.destroy();
    };
  }, [vantaEffect]);


  return (
    <div className="bg-blue-300 " ref={vantaRef}>
      <Head>
        <title>Angel Cruz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cloudy.png" />
      </Head>

      <main className="w-full h-full">
      <div className="p-4 overflow-hidden bg-transparent w-full text-center rounded-lg border-8 border-black shadow-md sm:p-8 dark:bg-gray-800 dark:border-gray-700 flex flex-col justify-center content-center" >
        <h1 className="text-blue-900 animate__animated animate__fadeInLeft text-6xl font-bold float-left">Howdy</h1>
        
        <p className="text-blue-900 text-5xl font-bold  mt-4">I&apos;m Angel Cruz</p>
        <p className="text-blue-900 text-5xl font-bold  mt-4">and I&apos;m currently a MEAN stack apprentice at <a className="text-black" href="https://bitwiseindustries.com/">Bitwise Industries</a></p>
        <a href="https://drive.google.com/file/d/1OEP6vRPZu3jY4_1t76YDtSP0Qvu_bd_Z/view?usp=sharing" target="_blank" rel="noopener noreferrer">
        <button className="bg-blue-700 hover:bg-transparent text-black font-bold h-20 w-32 border border-blue-700 rounded ">

  My Resume
</button>
</a>
        
        </div>
      </main>
      
    </div>
  )
}
